version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis-init:
    image: redis:7
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Running Redis init...';
        redis-cli -h redis < /redis/scripts/init_commands.txt;
        echo 'Init complete.';
      "
    volumes:
      - ./redis:/redis:ro
    restart: "no"
