version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10

  redis-init:
    image: redis:7
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: >
      sh -c "
        echo 'Running Redis init...';
        redis-cli -h redis < /redis/scripts/init_commands.txt;
        echo 'Init complete.';
      "
    volumes:
      - ./redis/scripts:/redis/scripts:ro
    restart: "no"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis-password
    volumes:
      - wandb-data:/app/data
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - api
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000

volumes:
  wandb-data:
