[project]
name = "two-towers-gigglers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "datasets>=2.14.4",
    "numpy==1.23",
    "pandas>=1.5.1",
    "torch==2.2.0",
]
